"""Regression tests for the `mm init` wizard (cli/init_cmd.py).

These tests pin down the shape of the `.mcp.json` generated by the wizard and
guard against a historical bug where MEMTOMEM_INDEXING__MEMORY_DIRS was written
as a plain string — which crashes the MCP server at startup because
pydantic-settings parses list-typed env vars as JSON arrays.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from memtomem.cli.init_cmd import _write_mcp_json
from memtomem.config import Mem2MemConfig


def test_write_mcp_json_omits_env_when_empty(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """When no env overrides are supplied, the generated .mcp.json must not
    include an empty or invalid `env` block. Settings come from
    ~/.memtomem/config.json at runtime instead."""
    monkeypatch.chdir(tmp_path)
    _write_mcp_json("uvx", ["--from", "memtomem", "memtomem-server"], {})

    data = json.loads((tmp_path / ".mcp.json").read_text(encoding="utf-8"))
    server = data["mcpServers"]["memtomem"]
    assert server["command"] == "uvx"
    assert server["args"] == ["--from", "memtomem", "memtomem-server"]
    assert "env" not in server, (
        "wizard must not write an empty/invalid env block — regression for "
        "the MEMTOMEM_INDEXING__MEMORY_DIRS plain-string bug"
    )


def test_write_mcp_json_preserves_valid_env(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """If a caller does pass env overrides, they round-trip unchanged."""
    monkeypatch.chdir(tmp_path)
    env = {"MEMTOMEM_TOOL_MODE": "standard"}
    _write_mcp_json("uvx", ["--from", "memtomem", "memtomem-server"], env)

    data = json.loads((tmp_path / ".mcp.json").read_text(encoding="utf-8"))
    assert data["mcpServers"]["memtomem"]["env"] == env


def _make_init_state(tmp_path: Path) -> dict:
    """Return a minimal wizard state dict pointing at *tmp_path*."""
    return {
        "provider": "none",
        "model": "",
        "dimension": 0,
        "db_path": str(tmp_path / "memtomem.db"),
        "memory_dir": str(tmp_path / "memories"),
        "enable_auto_ns": False,
        "default_ns": "default",
        "top_k": 10,
        "tokenizer": "unicode61",
        "decay_enabled": False,
        "rerank_enabled": False,
        # Non-config keys required by _write_config_and_summary
        "mcp_choice": 3,  # skip MCP setup
        "settings_hooks": False,
        "source_install": False,
        "source_dir": None,
        "project_install": False,
        "project_dir": None,
    }


class TestInitConfigMerge:
    """mm init must preserve non-init fields on re-run."""

    def test_reinit_preserves_existing_mutable_fields(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Post-init config changes (e.g. mmr.lambda_param) must survive re-init."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        # Redirect ~/.memtomem to tmp_path/.memtomem
        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()

        # First init
        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        # User modifies config post-init (simulate mm config set)
        config_path = config_dir / "config.json"
        data = json.loads(config_path.read_text(encoding="utf-8"))
        data["mmr"] = {"enabled": True, "lambda_param": 0.3}
        data["search"]["bm25_candidates"] = 200
        config_path.write_text(json.dumps(data, indent=2), encoding="utf-8")

        # Re-run init (change provider)
        state["provider"] = "onnx"
        state["model"] = "all-MiniLM-L6-v2"
        state["dimension"] = 384
        _write_config_and_summary(state, tmp_path)

        result = json.loads(config_path.read_text(encoding="utf-8"))

        # Init fields updated
        assert result["embedding"]["provider"] == "onnx"
        assert result["embedding"]["dimension"] == 384

        # Non-init fields preserved
        assert result["mmr"]["enabled"] is True
        assert result["mmr"]["lambda_param"] == 0.3
        assert result["search"]["bm25_candidates"] == 200

    def test_first_init_works_without_existing_config(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """First init (no config.json) must work exactly as before."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        config_path = config_dir / "config.json"
        data = json.loads(config_path.read_text(encoding="utf-8"))
        assert data["embedding"]["provider"] == "none"
        assert data["search"]["default_top_k"] == 10


class TestRerankerStep:
    """`_step_reranker` writes an optional `rerank` section into config.json."""

    def test_rerank_disabled_writes_no_section(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """When the user skips the reranker step, config.json must not gain a
        `rerank` section (so defaults remain in effect and re-init doesn't
        resurrect a stale enabled flag)."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        assert "rerank" not in data

    def test_rerank_enabled_writes_multilingual_model(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Enabling reranker with multilingual model writes provider=fastembed
        and the jina multilingual model ID."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        state = _make_init_state(tmp_path)
        state["rerank_enabled"] = True
        state["rerank_model"] = "jinaai/jina-reranker-v2-base-multilingual"
        _write_config_and_summary(state, tmp_path)

        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        assert data["rerank"] == {
            "enabled": True,
            "provider": "fastembed",
            "model": "jinaai/jina-reranker-v2-base-multilingual",
        }

    def test_rerank_disabled_preserves_existing_rerank_fields(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Re-running init with reranker disabled must not clobber a rerank
        section the user added manually (e.g. custom top_k)."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"
        config_path.write_text(
            json.dumps({"rerank": {"enabled": True, "top_k": 50}}),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        data = json.loads(config_path.read_text(encoding="utf-8"))
        assert data["rerank"]["enabled"] is True
        assert data["rerank"]["top_k"] == 50


def test_write_config_and_summary_without_base_dir_falls_back_to_home(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``_write_config_and_summary`` must be callable without *base_dir*.

    The interactive wizard's final step (``init_cmd.py:604``) invokes this
    helper with no ``base_dir``, relying on the ``Path.home()`` fallback.
    A previous refactor dropped the parameter default, making the call
    crash with ``TypeError: missing 1 required positional argument`` —
    this test pins the no-arg call as part of the contract.
    """
    from memtomem.cli.init_cmd import _write_config_and_summary

    monkeypatch.setenv("HOME", str(tmp_path))

    state = _make_init_state(tmp_path)
    _write_config_and_summary(state)

    assert (tmp_path / ".memtomem" / "config.json").exists()


class TestPreservedSummary:
    """`_write_config_and_summary` flags non-default values that the wizard
    inherited from a previous config but did not ask about this run.

    Primary driver: Web UI's `save_config_overrides` dumps all mutable fields
    to config.json whenever memory-dirs are changed or a section is saved,
    silently persisting runtime values (e.g. mmr.enabled) that the user may
    not have deliberately set. The wizard cannot fix the write path, but it
    can surface the leftovers on the next `mm init`."""

    def test_fresh_init_no_mmr_section(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Fresh init must not create an ``mmr`` section in config.json.

        This is the load-bearing guard: if anyone later wires the wizard to
        write to ``mmr.*``, this test fails and forces a deliberate update to
        the preserved-summary logic (since ``wizard_touched_keys`` would then
        need to include ``mmr.*`` to avoid flagging the user's own choice)."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        assert "mmr" not in data, (
            "wizard must not create an mmr section on fresh init — "
            "if you intentionally added an MMR step, update wizard_touched_keys"
        )

    def test_preserved_non_default_shown_in_summary(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """A pre-existing ``mmr.enabled=true`` (non-default) must surface in
        the Preserved block with the ``[!]`` marker."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        (config_dir / "config.json").write_text(
            json.dumps({"mmr": {"enabled": True, "lambda_param": 0.7}}),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        assert "Preserved from existing config" in out
        assert "[!] mmr.enabled = true" in out
        assert "built-in default: false" in out

    def test_preserved_default_not_shown(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """A preserved value equal to the built-in default must NOT be flagged
        — otherwise the Preserved block becomes noise on every re-run."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        (config_dir / "config.json").write_text(
            # mmr.enabled=False is the built-in default — should stay silent.
            json.dumps({"mmr": {"enabled": False, "lambda_param": 0.7}}),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        assert "Preserved from existing config" not in out
        assert "mmr.enabled" not in out

    def test_wizard_choice_overrides_preserved(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """A field the wizard actively writes this run (e.g. search.tokenizer)
        must appear in the normal summary, never in Preserved — even if the
        previous config had the same key set."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        (config_dir / "config.json").write_text(
            json.dumps({"search": {"tokenizer": "unicode61"}}),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        state["tokenizer"] = "kiwipiepy"
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        # Preserved block, if emitted, must NOT list tokenizer — wizard owns it
        preserved_idx = out.find("Preserved from existing config")
        if preserved_idx != -1:
            preserved_tail = out[preserved_idx:]
            assert "search.tokenizer" not in preserved_tail
        # And the normal summary shows the new choice
        assert "tokenizer=kiwipiepy" in out

    def test_malformed_config_graceful(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """A corrupt config.json must not crash the wizard. The bad file gets
        backed up with a ``.bak-<ts>`` suffix and the run proceeds as if
        ``existing`` were empty."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"
        config_path.write_text("{this is not json", encoding="utf-8")

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        assert "unreadable" in out
        # Backup created (suffix .json.bak-<ts>)
        backups = list(config_dir.glob("config.json.bak-*"))
        assert len(backups) == 1, f"expected exactly one backup, got {backups}"
        # New config is valid JSON
        data = json.loads(config_path.read_text(encoding="utf-8"))
        assert data["embedding"]["provider"] == "none"


def test_memory_dirs_env_requires_json_array(monkeypatch: pytest.MonkeyPatch) -> None:
    """Documentation examples of MEMTOMEM_INDEXING__MEMORY_DIRS must be
    encoded as a JSON array string. A bare path crashes pydantic-settings.

    This also guards the `mm init` wizard: previously it wrote a plain-string
    env var into `.mcp.json`, causing the MCP server to fail on startup with
    `SettingsError: error parsing value for field "indexing"`.
    """
    # Clear any inherited state first.
    monkeypatch.delenv("MEMTOMEM_INDEXING__MEMORY_DIRS", raising=False)
    # Prevent ~/.memtomem/config.json overrides from masking env-var behavior.
    import memtomem.config as _cfg

    monkeypatch.setattr(_cfg, "load_config_overrides", lambda c: None)

    # The documented format (JSON array literal) must parse cleanly.
    monkeypatch.setenv("MEMTOMEM_INDEXING__MEMORY_DIRS", '["~/notes"]')
    cfg = Mem2MemConfig()
    assert cfg.indexing.memory_dirs == [Path("~/notes")]

    # The bad format (plain string) must fail — this is the bug the docs and
    # wizard previously produced.
    monkeypatch.setenv("MEMTOMEM_INDEXING__MEMORY_DIRS", "~/notes")
    with pytest.raises(Exception):  # noqa: BLE001 — pydantic SettingsError wraps JSONDecodeError
        Mem2MemConfig()
