"""Regression tests for the `mm init` wizard (cli/init_cmd.py).

These tests pin down the shape of the `.mcp.json` generated by the wizard and
guard against a historical bug where MEMTOMEM_INDEXING__MEMORY_DIRS was written
as a plain string — which crashes the MCP server at startup because
pydantic-settings parses list-typed env vars as JSON arrays.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from memtomem.cli.init_cmd import _write_mcp_json
from memtomem.config import Mem2MemConfig


def test_write_mcp_json_omits_env_when_empty(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """When no env overrides are supplied, the generated .mcp.json must not
    include an empty or invalid `env` block. Settings come from
    ~/.memtomem/config.json at runtime instead."""
    monkeypatch.chdir(tmp_path)
    _write_mcp_json("uvx", ["--from", "memtomem", "memtomem-server"], {})

    data = json.loads((tmp_path / ".mcp.json").read_text(encoding="utf-8"))
    server = data["mcpServers"]["memtomem"]
    assert server["command"] == "uvx"
    assert server["args"] == ["--from", "memtomem", "memtomem-server"]
    assert "env" not in server, (
        "wizard must not write an empty/invalid env block — regression for "
        "the MEMTOMEM_INDEXING__MEMORY_DIRS plain-string bug"
    )


def test_write_mcp_json_preserves_valid_env(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """If a caller does pass env overrides, they round-trip unchanged."""
    monkeypatch.chdir(tmp_path)
    env = {"MEMTOMEM_TOOL_MODE": "standard"}
    _write_mcp_json("uvx", ["--from", "memtomem", "memtomem-server"], env)

    data = json.loads((tmp_path / ".mcp.json").read_text(encoding="utf-8"))
    assert data["mcpServers"]["memtomem"]["env"] == env


def test_memory_dirs_env_requires_json_array(monkeypatch: pytest.MonkeyPatch) -> None:
    """Documentation examples of MEMTOMEM_INDEXING__MEMORY_DIRS must be
    encoded as a JSON array string. A bare path crashes pydantic-settings.

    This also guards the `mm init` wizard: previously it wrote a plain-string
    env var into `.mcp.json`, causing the MCP server to fail on startup with
    `SettingsError: error parsing value for field "indexing"`.
    """
    # Clear any inherited state first.
    monkeypatch.delenv("MEMTOMEM_INDEXING__MEMORY_DIRS", raising=False)
    # Prevent ~/.memtomem/config.json overrides from masking env-var behavior.
    import memtomem.config as _cfg

    monkeypatch.setattr(_cfg, "load_config_overrides", lambda c: None)

    # The documented format (JSON array literal) must parse cleanly.
    monkeypatch.setenv("MEMTOMEM_INDEXING__MEMORY_DIRS", '["~/notes"]')
    cfg = Mem2MemConfig()
    assert cfg.indexing.memory_dirs == [Path("~/notes")]

    # The bad format (plain string) must fail — this is the bug the docs and
    # wizard previously produced.
    monkeypatch.setenv("MEMTOMEM_INDEXING__MEMORY_DIRS", "~/notes")
    with pytest.raises(Exception):  # noqa: BLE001 — pydantic SettingsError wraps JSONDecodeError
        Mem2MemConfig()
