"""Regression tests for the `mm init` wizard (cli/init_cmd.py).

These tests pin down the shape of the `.mcp.json` generated by the wizard and
guard against a historical bug where MEMTOMEM_INDEXING__MEMORY_DIRS was written
as a plain string — which crashes the MCP server at startup because
pydantic-settings parses list-typed env vars as JSON arrays.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from memtomem.cli.init_cmd import _write_mcp_json
from memtomem.config import Mem2MemConfig


def test_write_mcp_json_omits_env_when_empty(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """When no env overrides are supplied, the generated .mcp.json must not
    include an empty or invalid `env` block. Settings come from
    ~/.memtomem/config.json at runtime instead."""
    monkeypatch.chdir(tmp_path)
    _write_mcp_json("uvx", ["--from", "memtomem", "memtomem-server"], {})

    data = json.loads((tmp_path / ".mcp.json").read_text(encoding="utf-8"))
    server = data["mcpServers"]["memtomem"]
    assert server["command"] == "uvx"
    assert server["args"] == ["--from", "memtomem", "memtomem-server"]
    assert "env" not in server, (
        "wizard must not write an empty/invalid env block — regression for "
        "the MEMTOMEM_INDEXING__MEMORY_DIRS plain-string bug"
    )


def test_write_mcp_json_preserves_valid_env(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """If a caller does pass env overrides, they round-trip unchanged."""
    monkeypatch.chdir(tmp_path)
    env = {"MEMTOMEM_TOOL_MODE": "standard"}
    _write_mcp_json("uvx", ["--from", "memtomem", "memtomem-server"], env)

    data = json.loads((tmp_path / ".mcp.json").read_text(encoding="utf-8"))
    assert data["mcpServers"]["memtomem"]["env"] == env


def _make_init_state(tmp_path: Path) -> dict:
    """Return a minimal wizard state dict pointing at *tmp_path*."""
    return {
        "provider": "none",
        "model": "",
        "dimension": 0,
        "db_path": str(tmp_path / "memtomem.db"),
        "memory_dir": str(tmp_path / "memories"),
        "enable_auto_ns": False,
        "default_ns": "default",
        "top_k": 10,
        "tokenizer": "unicode61",
        "decay_enabled": False,
        "rerank_enabled": False,
        # Non-config keys required by _write_config_and_summary
        "mcp_choice": 3,  # skip MCP setup
        "settings_hooks": False,
        "source_install": False,
        "source_dir": None,
        "project_install": False,
        "project_dir": None,
    }


class TestInitConfigMerge:
    """mm init must preserve non-init fields on re-run."""

    def test_reinit_preserves_existing_mutable_fields(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Post-init config changes (e.g. mmr.lambda_param) must survive re-init."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        # Redirect ~/.memtomem to tmp_path/.memtomem
        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()

        # First init
        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        # User modifies config post-init (simulate mm config set)
        config_path = config_dir / "config.json"
        data = json.loads(config_path.read_text(encoding="utf-8"))
        data["mmr"] = {"enabled": True, "lambda_param": 0.3}
        data["search"]["bm25_candidates"] = 200
        config_path.write_text(json.dumps(data, indent=2), encoding="utf-8")

        # Re-run init (change provider)
        state["provider"] = "onnx"
        state["model"] = "all-MiniLM-L6-v2"
        state["dimension"] = 384
        _write_config_and_summary(state, tmp_path)

        result = json.loads(config_path.read_text(encoding="utf-8"))

        # Init fields updated
        assert result["embedding"]["provider"] == "onnx"
        assert result["embedding"]["dimension"] == 384

        # Non-init fields preserved
        assert result["mmr"]["enabled"] is True
        assert result["mmr"]["lambda_param"] == 0.3
        assert result["search"]["bm25_candidates"] == 200

    def test_first_init_works_without_existing_config(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """First init (no config.json) must work exactly as before."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        config_path = config_dir / "config.json"
        data = json.loads(config_path.read_text(encoding="utf-8"))
        assert data["embedding"]["provider"] == "none"
        assert data["search"]["default_top_k"] == 10


class TestRerankerStep:
    """`_step_reranker` writes an optional `rerank` section into config.json."""

    def test_rerank_disabled_writes_no_section(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """When the user skips the reranker step, config.json must not gain a
        `rerank` section (so defaults remain in effect and re-init doesn't
        resurrect a stale enabled flag)."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        assert "rerank" not in data

    def test_rerank_enabled_writes_multilingual_model(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Enabling reranker with multilingual model writes provider=fastembed
        and the jina multilingual model ID."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        state = _make_init_state(tmp_path)
        state["rerank_enabled"] = True
        state["rerank_model"] = "jinaai/jina-reranker-v2-base-multilingual"
        _write_config_and_summary(state, tmp_path)

        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        assert data["rerank"] == {
            "enabled": True,
            "provider": "fastembed",
            "model": "jinaai/jina-reranker-v2-base-multilingual",
        }

    def test_rerank_disabled_preserves_existing_rerank_fields(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Re-running init with reranker disabled must not clobber a rerank
        section the user added manually (e.g. custom top_k)."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"
        config_path.write_text(
            json.dumps({"rerank": {"enabled": True, "top_k": 50}}),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        data = json.loads(config_path.read_text(encoding="utf-8"))
        assert data["rerank"]["enabled"] is True
        assert data["rerank"]["top_k"] == 50


def test_write_config_and_summary_without_base_dir_falls_back_to_home(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``_write_config_and_summary`` must be callable without *base_dir*.

    The interactive wizard's final step (``init_cmd.py:604``) invokes this
    helper with no ``base_dir``, relying on the ``Path.home()`` fallback.
    A previous refactor dropped the parameter default, making the call
    crash with ``TypeError: missing 1 required positional argument`` —
    this test pins the no-arg call as part of the contract.
    """
    from memtomem.cli.init_cmd import _write_config_and_summary

    monkeypatch.setenv("HOME", str(tmp_path))

    state = _make_init_state(tmp_path)
    _write_config_and_summary(state)

    assert (tmp_path / ".memtomem" / "config.json").exists()


class TestPreservedSummary:
    """`_write_config_and_summary` flags non-default values that the wizard
    inherited from a previous config but did not ask about this run.

    Primary driver: Web UI's `save_config_overrides` dumps all mutable fields
    to config.json whenever memory-dirs are changed or a section is saved,
    silently persisting runtime values (e.g. mmr.enabled) that the user may
    not have deliberately set. The wizard cannot fix the write path, but it
    can surface the leftovers on the next `mm init`."""

    def test_fresh_init_no_mmr_section(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Fresh init must not create an ``mmr`` section in config.json.

        This is the load-bearing guard: if anyone later wires the wizard to
        write to ``mmr.*``, this test fails and forces a deliberate update to
        the preserved-summary logic (since ``wizard_touched_keys`` would then
        need to include ``mmr.*`` to avoid flagging the user's own choice)."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        assert "mmr" not in data, (
            "wizard must not create an mmr section on fresh init — "
            "if you intentionally added an MMR step, update wizard_touched_keys"
        )

    def test_preserved_non_default_shown_in_summary(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """A pre-existing ``mmr.enabled=true`` (non-default) must surface in
        the Preserved block with the ``[!]`` marker."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        (config_dir / "config.json").write_text(
            json.dumps({"mmr": {"enabled": True, "lambda_param": 0.7}}),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        assert "Preserved from existing config" in out
        assert "[!] mmr.enabled = true" in out
        assert "built-in default: false" in out

    def test_preserved_default_not_shown(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """A preserved value equal to the built-in default must NOT be flagged
        — otherwise the Preserved block becomes noise on every re-run."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        (config_dir / "config.json").write_text(
            # mmr.enabled=False is the built-in default — should stay silent.
            json.dumps({"mmr": {"enabled": False, "lambda_param": 0.7}}),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        assert "Preserved from existing config" not in out
        assert "mmr.enabled" not in out

    def test_wizard_choice_overrides_preserved(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """A field the wizard actively writes this run (e.g. search.tokenizer)
        must appear in the normal summary, never in Preserved — even if the
        previous config had the same key set."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        (config_dir / "config.json").write_text(
            json.dumps({"search": {"tokenizer": "unicode61"}}),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        state["tokenizer"] = "kiwipiepy"
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        # Preserved block, if emitted, must NOT list tokenizer — wizard owns it
        preserved_idx = out.find("Preserved from existing config")
        if preserved_idx != -1:
            preserved_tail = out[preserved_idx:]
            assert "search.tokenizer" not in preserved_tail
        # And the normal summary shows the new choice
        assert "tokenizer=kiwipiepy" in out

    def test_malformed_config_graceful(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """A corrupt config.json must not crash the wizard. The bad file gets
        backed up with a ``.bak-<ts>`` suffix and the run proceeds as if
        ``existing`` were empty."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"
        config_path.write_text("{this is not json", encoding="utf-8")

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        assert "unreadable" in out
        # Backup created (suffix .json.bak-<ts>)
        backups = list(config_dir.glob("config.json.bak-*"))
        assert len(backups) == 1, f"expected exactly one backup, got {backups}"
        # New config is valid JSON
        data = json.loads(config_path.read_text(encoding="utf-8"))
        assert data["embedding"]["provider"] == "none"


class TestFreshFlag:
    """``mm init --fresh`` drops wizard-untouched canonical leftovers
    instead of merely flagging them in the Preserved block.

    Phase 2 of the leftover-cleanup work (Phase 1 = surface; Phase 2 =
    reset). Critical guards:
      - never wipes user data / credentials (preserve list)
      - always backs up before dropping anything
      - idempotent: second run with nothing to drop is a no-op on disk
      - keys outside the canonical Mem2MemConfig shape are preserved"""

    def test_fresh_drops_preserved_mmr(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """Seed ``mmr.enabled=true`` (non-default, wizard-untouched) and run
        ``--fresh``: the key disappears, the section is pruned, a backup is
        written, and the Reset block names the change in
        ``before → after (default)`` form."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"
        # Seed only the non-default key — default-matching siblings (e.g.
        # lambda_param=0.7) wouldn't be dropped by --fresh anyway, and would
        # keep the section from being pruned, hiding the assertion below.
        config_path.write_text(
            json.dumps({"mmr": {"enabled": True}}),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path, fresh=True)

        data = json.loads(config_path.read_text(encoding="utf-8"))
        # mmr.enabled non-default → dropped; section becomes empty → pruned.
        assert "mmr" not in data, "mmr section should be pruned after --fresh"

        backups = list(config_dir.glob("config.json.bak-*"))
        assert len(backups) == 1, f"expected one backup, got {backups}"

        out = unstyle(capsys.readouterr().out)
        assert "Reset to default" in out
        assert "[-] mmr.enabled: true → false (default)" in out
        assert f"Backup saved to: {backups[0]}" in out
        assert "restart it to pick up the new config" in out

    @pytest.mark.parametrize(
        "key,value",
        [
            # Credentials
            ("embedding.api_key", "sk-test-xxx"),
            ("rerank.api_key", "voyage-xxx"),
            ("llm.api_key", "anthropic-xxx"),
            ("webhook.secret", "hmac-secret"),
            # Endpoints
            ("embedding.base_url", "https://my-openai-proxy/v1"),
            ("llm.base_url", "http://my-llm:8080"),
            ("webhook.url", "https://ops.example.com/hook"),
            # User-curated lists / rules
            ("indexing.exclude_patterns", ["*.tmp", "node_modules/"]),
            ("indexing.supported_extensions", [".rst", ".org"]),
            (
                "namespace.rules",
                [{"path_glob": "work/**", "namespace": "work"}],
            ),
            ("search.system_namespace_prefixes", ["__system__:"]),
            ("webhook.events", ["add"]),
        ],
    )
    def test_fresh_preserves_user_data_keys(
        self,
        key: str,
        value: object,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """Each key in ``_FRESH_PRESERVE_KEYS`` must survive ``--fresh`` even
        when it's non-default and wizard-untouched. This is the structural
        guard tying the parametrize list to the preserve-list constant —
        adding a new key to one without the other will fail this test."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"

        # Seed the single user-data key into a nested config dict.
        seed: dict = {}
        cur: dict = seed
        parts = key.split(".")
        for p in parts[:-1]:
            cur = cur.setdefault(p, {})
        cur[parts[-1]] = value
        config_path.write_text(json.dumps(seed), encoding="utf-8")

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path, fresh=True)

        data = json.loads(config_path.read_text(encoding="utf-8"))
        cur2: object = data
        for p in parts:
            assert isinstance(cur2, dict) and p in cur2, (
                f"--fresh wiped preserve-list key {key!r}; preserve list and "
                "test parametrize have drifted apart"
            )
            cur2 = cur2[p]
        assert cur2 == value, f"value for {key!r} mutated: {cur2!r} != {value!r}"

    def test_fresh_preserves_memory_dirs(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """``indexing.memory_dirs`` is wizard-touched (the wizard always
        rewrites it from ``state['memory_dir']``), so ``--fresh`` must NOT
        list it as a drop candidate. The wizard's overwrite is independent
        of ``--fresh`` and is not under test here.

        Guard against a future refactor that moves memory_dirs out of
        ``init_data`` — that would silently make ``--fresh`` a memory-dir
        wiper, which is the most surprising data-loss path."""
        from memtomem.cli.init_cmd import (
            _compute_fresh_drops,
            _flatten_init_data_keys,
            _write_config_and_summary,
        )

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"
        config_path.write_text(
            json.dumps({"indexing": {"memory_dirs": ["~/notes", "~/docs"]}}),
            encoding="utf-8",
        )

        # Verify _compute_fresh_drops never selects memory_dirs (wizard-touched).
        state = _make_init_state(tmp_path)
        init_data_shape = {
            "embedding": {},
            "indexing": {"memory_dirs": []},
            "namespace": {},
            "search": {},
            "decay": {},
            "storage": {},
        }
        wizard_touched = _flatten_init_data_keys(init_data_shape)
        assert "indexing.memory_dirs" in wizard_touched, (
            "wizard_touched_keys must include indexing.memory_dirs — if it "
            "doesn't, --fresh would wipe user memory dirs"
        )

        existing_seed = {"indexing": {"memory_dirs": ["~/notes", "~/docs"]}}
        drops = _compute_fresh_drops(existing_seed, wizard_touched)
        assert all(k != "indexing.memory_dirs" for k, _, _ in drops), (
            "indexing.memory_dirs leaked into --fresh drop set"
        )

        # End-to-end: --fresh with memory_dirs seed completes without wiping
        # data (the wizard then overwrites it from state, which is expected).
        _write_config_and_summary(state, tmp_path, fresh=True)
        data = json.loads(config_path.read_text(encoding="utf-8"))
        assert "indexing" in data and "memory_dirs" in data["indexing"]

    def test_fresh_keeps_user_custom_keys(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A custom key outside the canonical ``Mem2MemConfig`` shape must
        survive ``--fresh`` regardless of preserve-list contents — drop logic
        only considers canonical keys."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"
        config_path.write_text(
            json.dumps(
                {
                    "my_extension": {"foo": 1, "bar": "two"},
                    "mmr": {"enabled": True},
                }
            ),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path, fresh=True)

        data = json.loads(config_path.read_text(encoding="utf-8"))
        assert data.get("my_extension") == {"foo": 1, "bar": "two"}
        # Canonical leftover still gets dropped.
        assert "mmr" not in data

    def test_fresh_no_op_when_nothing_to_reset(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """If the existing config has no wizard-untouched non-default keys,
        ``--fresh`` writes no backup and prints the no-leftovers message."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        # Seed only fields the wizard will overwrite — nothing untouched
        # that differs from default.
        config_path = config_dir / "config.json"
        config_path.write_text(
            json.dumps({"embedding": {"provider": "ollama"}}),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path, fresh=True)

        backups = list(config_dir.glob("config.json.bak-*"))
        assert backups == [], f"unexpected backup created: {backups}"

        out = unstyle(capsys.readouterr().out)
        assert "no wizard-untouched leftovers to reset" in out
        assert "Reset to default" not in out

    def test_fresh_with_non_interactive(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """``--fresh`` is compatible with ``-y`` (non-interactive) — drops
        proceed without any prompt, the Reset block still prints, and the
        normal Setup-complete summary is unaffected."""
        from click import unstyle
        from click.testing import CliRunner

        from memtomem.cli.init_cmd import init

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"
        config_path.write_text(
            json.dumps({"mmr": {"enabled": True}}),
            encoding="utf-8",
        )

        result = CliRunner().invoke(
            init,
            ["-y", "--fresh", "--provider", "none", "--memory-dir", str(tmp_path / "mem")],
        )
        assert result.exit_code == 0, result.output

        out = unstyle(result.output)
        assert "Reset to default" in out
        assert "Setup complete!" in out  # Phase 1 summary still emitted

        data = json.loads(config_path.read_text(encoding="utf-8"))
        assert "mmr" not in data

    def test_fresh_handles_malformed_config(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """Malformed ``config.json`` + ``--fresh`` falls through to the
        existing unreadable-config recovery path (timestamped backup +
        empty merge base) and emits the no-leftovers Reset message — the
        post-recovery ``existing`` is empty so nothing is droppable."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"
        config_path.write_text("{not valid json", encoding="utf-8")

        state = _make_init_state(tmp_path)
        _write_config_and_summary(state, tmp_path, fresh=True)

        out = unstyle(capsys.readouterr().out)
        assert "unreadable" in out  # malformed-config recovery hit
        # The unreadable-config path creates exactly one backup (.bak-<ts>);
        # --fresh's own backup logic skips because no drops were possible.
        backups = list(config_dir.glob("config.json.bak-*"))
        assert len(backups) == 1, f"expected one backup, got {backups}"
        assert "no wizard-untouched leftovers to reset" in out

    def test_fresh_is_idempotent(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """Running ``--fresh`` twice in a row: first run drops + backs up,
        second run is a pure no-op on disk (no second backup, config
        bit-identical). Guard against accidental backup churn."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        # Pin time.time so a same-second double-invoke can't collide on
        # the .bak-<ts> filename even on fast machines.
        clock = {"t": 1_700_000_000}
        monkeypatch.setattr("memtomem.cli.init_cmd.time.time", lambda: clock["t"])

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"
        config_path.write_text(
            json.dumps({"mmr": {"enabled": True}, "search": {"rrf_k": 120}}),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)

        _write_config_and_summary(state, tmp_path, fresh=True)
        first_pass = config_path.read_text(encoding="utf-8")
        first_backups = sorted(config_dir.glob("config.json.bak-*"))
        assert len(first_backups) == 1

        clock["t"] += 1  # second run gets a different ts in case it backs up
        _write_config_and_summary(state, tmp_path, fresh=True)
        second_pass = config_path.read_text(encoding="utf-8")
        second_backups = sorted(config_dir.glob("config.json.bak-*"))

        assert second_pass == first_pass, "second --fresh run mutated config"
        assert second_backups == first_backups, (
            "second --fresh run created a backup despite zero drops"
        )

    def test_fresh_atomic_write_failure_keeps_backup_and_original(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """``--fresh`` now writes via ``_atomic_write_json``. If the atomic
        ``os.replace`` fails mid-write, both the pre-fresh ``config.json``
        and the backup must stay intact, and no ``.config.*.tmp`` orphan
        should linger in ``~/.memtomem/``. This is the failure-mode
        complement to ``test_fresh_drops_preserved_mmr``: the happy path is
        already covered there.
        """
        import os as _os

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        config_path = config_dir / "config.json"
        original = json.dumps({"mmr": {"enabled": True}})
        config_path.write_text(original, encoding="utf-8")

        def fail_replace(*args, **kwargs):
            raise OSError("simulated replace failure")

        monkeypatch.setattr(_os, "replace", fail_replace)

        state = _make_init_state(tmp_path)
        with pytest.raises(OSError, match="simulated replace failure"):
            _write_config_and_summary(state, tmp_path, fresh=True)

        assert config_path.read_text(encoding="utf-8") == original
        backups = list(config_dir.glob("config.json.bak-*"))
        assert len(backups) == 1, f"expected backup to survive, got {backups}"
        orphans = [
            p
            for p in config_dir.iterdir()
            if p.name.startswith(".config.") and p.name.endswith(".tmp")
        ]
        assert not orphans, f"orphan tmp file(s) after failed atomic write: {orphans}"


class TestMcpPasteHints:
    """The wizard's MCP step writes a Claude-Code-scoped ``.mcp.json`` and must
    surface what the user still has to do for Cursor / Windsurf / Claude
    Desktop / Gemini CLI (none of which auto-load the project file).

    Regression for #246: earlier wording implied ``.mcp.json`` is the config
    file for those editors, which it isn't — each has its own canonical path."""

    def test_choice_2_emits_per_editor_paste_hints(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        monkeypatch.chdir(tmp_path)

        state = _make_init_state(tmp_path)
        state["mcp_choice"] = 2
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        assert "MCP config: wrote ./.mcp.json" in out
        assert "Cursor" in out and "~/.cursor/mcp.json" in out
        assert "Windsurf" in out and "~/.codeium/windsurf/mcp_config.json" in out
        assert "Claude Desktop" in out
        assert "Library/Application Support/Claude/claude_desktop_config.json" in out
        assert "Gemini CLI" in out and "~/.gemini/settings.json" in out
        assert "Claude Code picks up ./.mcp.json in this project automatically" in out

    def test_choice_3_skip_emits_no_hints(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """Skipping MCP setup must not print paste hints — there's no file
        yet for the user to paste."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        state = _make_init_state(tmp_path)  # mcp_choice = 3 by default
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        assert "MCP config:" not in out
        assert "~/.cursor/mcp.json" not in out

    def test_step_mcp_menu_does_not_imply_autoload(
        self,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """The ``[2]`` menu line must scope ``.mcp.json`` to Claude Code and
        frame other editors as "copy into". The old "(for Cursor, Windsurf,
        etc.)" wording implied auto-compat and is explicitly ruled out."""
        from click import unstyle

        from memtomem.cli.init_cmd import _step_mcp

        # Stub the interactive prompt so the menu renders without stdin.
        monkeypatch.setattr("memtomem.cli.init_cmd.nav_prompt", lambda *a, **kw: 3)

        state: dict = {}
        _step_mcp(state)

        out = unstyle(capsys.readouterr().out)
        assert "(for Cursor, Windsurf, etc.)" not in out, "old auto-compat wording leaked back in"
        assert "Claude Code project scope" in out
        assert "copy into your editor's config file" in out


class TestProviderDirsStep:
    """Step 4 — opt-in indexing of provider memory folders.

    Replaces the legacy ``ensure_auto_discovered_dirs`` runtime path. The
    step is wizard-driven (per-category nav_confirm), and a non-interactive
    counterpart is exposed via ``--include-provider``.
    """

    def test_step_skips_when_no_provider_dirs_detected(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Detection returns all-empty → step records [] without prompting."""
        from memtomem.cli import init_cmd

        monkeypatch.setattr(
            "memtomem.config._detect_provider_dirs",
            lambda: {"claude-memory": [], "claude-plans": [], "codex": []},
        )
        # Failing nav_confirm guarantees the test breaks if a prompt fires.
        monkeypatch.setattr(
            init_cmd,
            "nav_confirm",
            lambda *a, **kw: pytest.fail("nav_confirm called when no dirs detected"),
        )

        state: dict = {}
        init_cmd._step_provider_dirs(state)
        assert state["provider_dirs"] == []

    def test_step_appends_only_accepted_categories(
        self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
    ) -> None:
        """User says yes to Claude memory and Codex, no to plans → only the
        accepted categories land in state["provider_dirs"]."""
        from memtomem.cli import init_cmd

        claude_mem = tmp_path / "claude-mem"
        plans = tmp_path / "plans"
        codex = tmp_path / "codex"
        for p in (claude_mem, plans, codex):
            p.mkdir()

        monkeypatch.setattr(
            "memtomem.config._detect_provider_dirs",
            lambda: {
                "claude-memory": [claude_mem],
                "claude-plans": [plans],
                "codex": [codex],
            },
        )
        # Order of prompts in _step_provider_dirs: claude-memory, claude-plans, codex
        answers = iter([True, False, True])
        monkeypatch.setattr(init_cmd, "nav_confirm", lambda *a, **kw: next(answers))

        state: dict = {}
        init_cmd._step_provider_dirs(state)
        assert state["provider_dirs"] == [str(claude_mem), str(codex)]

    def test_step_skips_categories_with_no_dirs(
        self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
    ) -> None:
        """Categories with no detected dirs do NOT get a prompt — only the
        present categories show up. Counts from the answers iterator are a
        load-bearing guard against an extra prompt sneaking in."""
        from memtomem.cli import init_cmd

        plans = tmp_path / "plans"
        plans.mkdir()
        monkeypatch.setattr(
            "memtomem.config._detect_provider_dirs",
            lambda: {"claude-memory": [], "claude-plans": [plans], "codex": []},
        )
        answers = iter([True])  # exactly one prompt expected (plans only)
        monkeypatch.setattr(init_cmd, "nav_confirm", lambda *a, **kw: next(answers))

        state: dict = {}
        init_cmd._step_provider_dirs(state)
        assert state["provider_dirs"] == [str(plans)]
        with pytest.raises(StopIteration):
            next(answers)  # no extra prompts fired

    def test_step_includes_multiple_claude_memory_projects(
        self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
    ) -> None:
        """A single 'yes' to Claude memory adds every detected per-project dir,
        not just the first — grouping the prompt avoids per-project noise."""
        from memtomem.cli import init_cmd

        p1 = tmp_path / "p1" / "memory"
        p2 = tmp_path / "p2" / "memory"
        for p in (p1, p2):
            p.mkdir(parents=True)
            (p / "MEMORY.md").write_text("# index", encoding="utf-8")

        monkeypatch.setattr(
            "memtomem.config._detect_provider_dirs",
            lambda: {"claude-memory": [p1, p2], "claude-plans": [], "codex": []},
        )
        monkeypatch.setattr(init_cmd, "nav_confirm", lambda *a, **kw: True)

        state: dict = {}
        init_cmd._step_provider_dirs(state)
        assert state["provider_dirs"] == [str(p1), str(p2)]

    def test_write_merges_provider_dirs_into_memory_dirs(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """``_write_config_and_summary`` concatenates ``state["memory_dir"]``
        with ``state["provider_dirs"]`` (deduped) when persisting
        ``indexing.memory_dirs``. Also pins ``auto_discover: false`` so a
        fresh wizard run on a legacy install doesn't keep migrating."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        provider_dir = tmp_path / "claude-mem"
        provider_dir.mkdir()

        state = _make_init_state(tmp_path)
        state["provider_dirs"] = [str(provider_dir)]
        _write_config_and_summary(state, tmp_path)

        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        dirs = data["indexing"]["memory_dirs"]
        assert state["memory_dir"] in dirs
        assert str(provider_dir) in dirs
        assert dirs.count(state["memory_dir"]) == 1  # no duplicates
        assert data["indexing"]["auto_discover"] is False


class TestCategorizeMemoryDir:
    """Per-path classifier that powers both wizard grouping and the Web
    UI's ``category`` field on ``GET /api/memory-dirs/status``."""

    def test_claude_memory_per_project(self) -> None:
        from memtomem.config import categorize_memory_dir

        assert (
            categorize_memory_dir("/home/alice/.claude/projects/my-proj/memory") == "claude-memory"
        )

    def test_claude_plans(self) -> None:
        from memtomem.config import categorize_memory_dir

        assert categorize_memory_dir("/home/alice/.claude/plans") == "claude-plans"

    def test_codex_memories(self) -> None:
        from memtomem.config import categorize_memory_dir

        assert categorize_memory_dir("/home/alice/.codex/memories") == "codex"

    def test_trailing_slash_normalisation(self) -> None:
        from memtomem.config import categorize_memory_dir

        # Trailing slash(es) should not change the category.
        assert categorize_memory_dir("/u/.codex/memories/") == "codex"
        assert categorize_memory_dir("/u/.codex/memories///") == "codex"
        assert categorize_memory_dir("/u/.claude/plans/") == "claude-plans"

    def test_user_fallback(self) -> None:
        from memtomem.config import categorize_memory_dir

        assert categorize_memory_dir("/home/alice/notes") == "user"
        assert categorize_memory_dir("/srv/shared/memory") == "user"

    def test_lookalike_paths_do_not_match(self) -> None:
        """Paths that mention ``claude``/``codex`` but aren't the canonical
        provider layout must stay in ``user`` — classification is anchored
        at the end of the path, not a substring match."""
        from memtomem.config import categorize_memory_dir

        # Looks like a provider path but isn't — user took a backup/copy.
        assert categorize_memory_dir("/archive/.codex/memories-backup") == "user"
        # No leading dot — not the real ``.claude`` dir.
        assert categorize_memory_dir("/work/claude/plans/foo") == "user"
        # Extra suffix past the canonical name.
        assert categorize_memory_dir("/u/.claude/plans/2024") == "user"

    def test_pathlib_input(self, tmp_path: Path) -> None:
        """Accepts ``Path`` as well as ``str`` — the indexing stats call
        passes whatever is in the config list through verbatim."""
        from memtomem.config import categorize_memory_dir

        p = Path("/u/.codex/memories")
        assert categorize_memory_dir(p) == "codex"
        assert categorize_memory_dir(tmp_path) == "user"

    def test_provider_categories_tuple_is_derived(self) -> None:
        """Belt-and-suspenders: the exported category tuple is built from
        the same pattern table, so adding a row can't silently diverge."""
        from memtomem.config import (
            PROVIDER_DIR_CATEGORIES,
            _PROVIDER_CATEGORY_PATTERNS,
        )

        assert PROVIDER_DIR_CATEGORIES == tuple(cat for cat, _ in _PROVIDER_CATEGORY_PATTERNS)


class TestDetectProviderDirsRoundtrip:
    """Drift guard: every path ``_detect_provider_dirs`` returns must
    classify back to the same category via ``categorize_memory_dir``.

    Without this, the "single source of truth" claim of issue #299 is
    only enforced by code review — exactly the pattern called out in
    ``feedback_silent_policy_enforcement_gap.md``.
    """

    def test_roundtrip_over_all_categories(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        from memtomem.config import _detect_provider_dirs, categorize_memory_dir

        monkeypatch.setenv("HOME", str(tmp_path))

        # Populate one entry per category so every branch of detection
        # fires and every resulting Path goes through the classifier.
        proj_mem = tmp_path / ".claude" / "projects" / "demo" / "memory"
        proj_mem.mkdir(parents=True)
        (proj_mem / "note.md").write_text("x", encoding="utf-8")
        plans = tmp_path / ".claude" / "plans"
        plans.mkdir(parents=True)
        codex = tmp_path / ".codex" / "memories"
        codex.mkdir(parents=True)

        grouped = _detect_provider_dirs()

        seen_any = False
        for expected_cat, paths in grouped.items():
            for p in paths:
                seen_any = True
                assert categorize_memory_dir(p) == expected_cat, (
                    f"_detect_provider_dirs bucketed {p!r} as {expected_cat!r} "
                    f"but categorize_memory_dir classifies it as "
                    f"{categorize_memory_dir(p)!r}"
                )
        assert seen_any, "fixture should produce at least one discovered dir"


class TestIncludeProviderFlag:
    """Non-interactive ``--include-provider`` wires categories into
    ``indexing.memory_dirs`` without prompting."""

    def test_flag_resolves_categories_to_dirs(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        from click.testing import CliRunner

        from memtomem.cli.init_cmd import init

        monkeypatch.setenv("HOME", str(tmp_path))
        codex = tmp_path / "codex"
        codex.mkdir()
        monkeypatch.setattr(
            "memtomem.config._detect_provider_dirs",
            lambda: {"claude-memory": [], "claude-plans": [], "codex": [codex]},
        )

        runner = CliRunner()
        result = runner.invoke(
            init,
            [
                "--non-interactive",
                "--memory-dir",
                str(tmp_path / "memories"),
                "--include-provider",
                "codex",
                "--mcp",
                "skip",
            ],
        )
        assert result.exit_code == 0, result.output

        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        assert str(codex) in data["indexing"]["memory_dirs"]

    def test_flag_silently_skips_unavailable_categories(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Asking for a category with no detected dirs is a no-op, not an error."""
        from click.testing import CliRunner

        from memtomem.cli.init_cmd import init

        monkeypatch.setenv("HOME", str(tmp_path))
        monkeypatch.setattr(
            "memtomem.config._detect_provider_dirs",
            lambda: {"claude-memory": [], "claude-plans": [], "codex": []},
        )

        runner = CliRunner()
        result = runner.invoke(
            init,
            [
                "--non-interactive",
                "--memory-dir",
                str(tmp_path / "memories"),
                "--include-provider",
                "codex",
                "--mcp",
                "skip",
            ],
        )
        assert result.exit_code == 0, result.output
        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        # Only the user's primary memory_dir survives; no fake codex path.
        assert data["indexing"]["memory_dirs"] == [str(tmp_path / "memories")]

    def test_no_flag_writes_no_provider_dirs(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Without ``--include-provider``, non-interactive mode adds zero
        provider dirs even if the dev machine has them."""
        from click.testing import CliRunner

        from memtomem.cli.init_cmd import init

        monkeypatch.setenv("HOME", str(tmp_path))
        # Pretend a Codex dir exists; the test asserts it's NOT pulled in.
        codex = tmp_path / "codex"
        codex.mkdir()
        monkeypatch.setattr(
            "memtomem.config._detect_provider_dirs",
            lambda: {"claude-memory": [], "claude-plans": [], "codex": [codex]},
        )

        runner = CliRunner()
        result = runner.invoke(
            init,
            [
                "--non-interactive",
                "--memory-dir",
                str(tmp_path / "memories"),
                "--mcp",
                "skip",
            ],
        )
        assert result.exit_code == 0, result.output
        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        assert str(codex) not in data["indexing"]["memory_dirs"]


def test_memory_dirs_env_requires_json_array(monkeypatch: pytest.MonkeyPatch) -> None:
    """Documentation examples of MEMTOMEM_INDEXING__MEMORY_DIRS must be
    encoded as a JSON array string. A bare path crashes pydantic-settings.

    This also guards the `mm init` wizard: previously it wrote a plain-string
    env var into `.mcp.json`, causing the MCP server to fail on startup with
    `SettingsError: error parsing value for field "indexing"`.
    """
    # Clear any inherited state first.
    monkeypatch.delenv("MEMTOMEM_INDEXING__MEMORY_DIRS", raising=False)
    # Prevent ~/.memtomem/config.json overrides from masking env-var behavior.
    import memtomem.config as _cfg

    monkeypatch.setattr(_cfg, "load_config_overrides", lambda c: None)

    # The documented format (JSON array literal) must parse cleanly.
    monkeypatch.setenv("MEMTOMEM_INDEXING__MEMORY_DIRS", '["~/notes"]')
    cfg = Mem2MemConfig()
    assert cfg.indexing.memory_dirs == [Path("~/notes")]

    # The bad format (plain string) must fail — this is the bug the docs and
    # wizard previously produced.
    monkeypatch.setenv("MEMTOMEM_INDEXING__MEMORY_DIRS", "~/notes")
    with pytest.raises(Exception):  # noqa: BLE001 — pydantic SettingsError wraps JSONDecodeError
        Mem2MemConfig()


class TestProviderPresetRules:
    """Wizard appends matching ``NamespacePolicyRule`` entries to
    ``namespace.rules`` when the user accepts a provider category (#296).

    Without the preset, ``auto_ns`` collapses paths like
    ``~/.claude/projects/FOO/memory/foo.md`` to the ``default`` namespace
    because ``memory`` is a non-discriminating basename. The preset routes
    the file under ``claude:FOO`` via the ``{ancestor:1}`` placeholder.
    """

    @pytest.mark.parametrize(
        ("category", "expected_glob", "expected_ns"),
        [
            ("claude-memory", "~/.claude/projects/*/memory/**", "claude:{ancestor:1}"),
            ("claude-plans", "~/.claude/plans/**", "claude-plans"),
            ("codex", "~/.codex/memories/**", "codex"),
        ],
    )
    def test_step_collects_rule_for_accepted_category(
        self,
        monkeypatch: pytest.MonkeyPatch,
        tmp_path: Path,
        category: str,
        expected_glob: str,
        expected_ns: str,
    ) -> None:
        from memtomem.cli import init_cmd

        target = tmp_path / category
        target.mkdir()
        grouped = {"claude-memory": [], "claude-plans": [], "codex": []}
        grouped[category] = [target]
        monkeypatch.setattr("memtomem.config._detect_provider_dirs", lambda: grouped)
        monkeypatch.setattr(init_cmd, "nav_confirm", lambda *a, **kw: True)

        state: dict = {}
        init_cmd._step_provider_dirs(state)

        rules = state.get("provider_rules", [])
        assert len(rules) == 1
        cat, rule = rules[0]
        assert cat == category
        assert rule == {"path_glob": expected_glob, "namespace": expected_ns}

    def test_step_skips_rule_when_category_declined(
        self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
    ) -> None:
        from memtomem.cli import init_cmd

        codex = tmp_path / "codex"
        codex.mkdir()
        monkeypatch.setattr(
            "memtomem.config._detect_provider_dirs",
            lambda: {"claude-memory": [], "claude-plans": [], "codex": [codex]},
        )
        monkeypatch.setattr(init_cmd, "nav_confirm", lambda *a, **kw: False)

        state: dict = {}
        init_cmd._step_provider_dirs(state)
        assert state.get("provider_rules") == []

    def test_write_appends_preset_rules_to_config(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Accepted categories land as ``NamespacePolicyRule`` entries in
        the persisted ``namespace.rules`` list."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        state = _make_init_state(tmp_path)
        state["provider_rules"] = [
            (
                "claude-memory",
                {"path_glob": "~/.claude/projects/*/memory/**", "namespace": "claude:{ancestor:1}"},
            ),
            ("codex", {"path_glob": "~/.codex/memories/**", "namespace": "codex"}),
        ]
        _write_config_and_summary(state, tmp_path)

        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        rules = data["namespace"]["rules"]
        assert {
            "path_glob": "~/.claude/projects/*/memory/**",
            "namespace": "claude:{ancestor:1}",
        } in rules
        assert {"path_glob": "~/.codex/memories/**", "namespace": "codex"} in rules

    def test_write_is_idempotent_on_rerun(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Running ``mm init`` twice with the same accepted categories does
        not duplicate rules — dedup is by ``path_glob``."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        state = _make_init_state(tmp_path)
        state["provider_rules"] = [
            ("codex", {"path_glob": "~/.codex/memories/**", "namespace": "codex"}),
        ]

        _write_config_and_summary(state, tmp_path)
        _write_config_and_summary(state, tmp_path)

        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        rules = data["namespace"]["rules"]
        matching = [r for r in rules if r.get("path_glob") == "~/.codex/memories/**"]
        assert len(matching) == 1, f"expected one codex rule, got {matching}"

    def test_write_preserves_user_rule_on_same_glob_diff_namespace(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """User-authored rule with the preset's ``path_glob`` but a custom
        ``namespace`` wins — the wizard does not overwrite it."""
        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        # Seed config with a user-authored rule using the preset's glob.
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        (config_dir / "config.json").write_text(
            json.dumps(
                {
                    "namespace": {
                        "rules": [{"path_glob": "~/.codex/memories/**", "namespace": "my-codex"}]
                    }
                }
            ),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        state["provider_rules"] = [
            ("codex", {"path_glob": "~/.codex/memories/**", "namespace": "codex"}),
        ]
        _write_config_and_summary(state, tmp_path)

        data = json.loads((config_dir / "config.json").read_text(encoding="utf-8"))
        rules = data["namespace"]["rules"]
        assert len(rules) == 1
        assert rules[0]["namespace"] == "my-codex", "user override should be preserved"

    def test_dedup_expanduser_normalizes_both_sides(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """``~/.codex/memories/**`` and the expanded absolute form are
        treated as the same rule for dedup purposes so manually edited
        configs stay idempotent under ``mm init`` re-runs."""
        from memtomem.cli.init_cmd import _rule_matches_existing

        existing = [
            {"path_glob": str(Path("~/.codex/memories/**").expanduser()), "namespace": "codex"},
        ]
        assert _rule_matches_existing("~/.codex/memories/**", existing) is True
        assert _rule_matches_existing("~/.claude/plans/**", existing) is False

    def test_include_provider_flag_writes_rule_when_dirs_present(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Non-interactive ``--include-provider`` parity: rule is appended
        the same way as the interactive per-category prompt."""
        from click.testing import CliRunner

        from memtomem.cli.init_cmd import init

        monkeypatch.setenv("HOME", str(tmp_path))
        codex = tmp_path / "codex"
        codex.mkdir()
        monkeypatch.setattr(
            "memtomem.config._detect_provider_dirs",
            lambda: {"claude-memory": [], "claude-plans": [], "codex": [codex]},
        )

        result = CliRunner().invoke(
            init,
            [
                "--non-interactive",
                "--memory-dir",
                str(tmp_path / "memories"),
                "--include-provider",
                "codex",
                "--mcp",
                "skip",
            ],
        )
        assert result.exit_code == 0, result.output
        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        rules = data["namespace"]["rules"]
        assert any(r.get("path_glob") == "~/.codex/memories/**" for r in rules)

    def test_include_provider_flag_skips_rule_when_no_dirs(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Asking for a category whose dirs don't exist on this machine
        does NOT register a rule — parity with the interactive step skipping
        empty categories keeps config clean of dead rules."""
        from click.testing import CliRunner

        from memtomem.cli.init_cmd import init

        monkeypatch.setenv("HOME", str(tmp_path))
        monkeypatch.setattr(
            "memtomem.config._detect_provider_dirs",
            lambda: {"claude-memory": [], "claude-plans": [], "codex": []},
        )

        result = CliRunner().invoke(
            init,
            [
                "--non-interactive",
                "--memory-dir",
                str(tmp_path / "memories"),
                "--include-provider",
                "codex",
                "--mcp",
                "skip",
            ],
        )
        assert result.exit_code == 0, result.output
        data = json.loads((tmp_path / ".memtomem" / "config.json").read_text(encoding="utf-8"))
        rules = data.get("namespace", {}).get("rules", [])
        assert rules == []

    def test_banner_lists_proposed_and_skipped(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """Banner shows `+` for new rules and `⏭` for skipped (existing).
        Pre-write output so a partial failure surfaces what was attempted."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        # Seed: codex rule already present, claude-plans not.
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        (config_dir / "config.json").write_text(
            json.dumps(
                {
                    "namespace": {
                        "rules": [{"path_glob": "~/.codex/memories/**", "namespace": "codex"}]
                    }
                }
            ),
            encoding="utf-8",
        )

        state = _make_init_state(tmp_path)
        state["provider_rules"] = [
            ("claude-plans", {"path_glob": "~/.claude/plans/**", "namespace": "claude-plans"}),
            ("codex", {"path_glob": "~/.codex/memories/**", "namespace": "codex"}),
        ]
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        assert "Namespace rules:" in out
        assert "+ ~/.claude/plans/**" in out
        assert "⏭ ~/.codex/memories/**" in out

    def test_banner_silent_when_no_proposals(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """No accepted categories → no banner noise."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        state = _make_init_state(tmp_path)
        state["provider_rules"] = []
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        assert "Namespace rules:" not in out

    def test_banner_all_skipped_one_liner(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """Every proposed rule already exists → one-liner confirms the
        wizard looked, instead of staying silent and leaving the user to
        wonder whether rules were considered at all."""
        from click import unstyle

        from memtomem.cli.init_cmd import _write_config_and_summary

        monkeypatch.setenv("HOME", str(tmp_path))
        config_dir = tmp_path / ".memtomem"
        config_dir.mkdir()
        (config_dir / "config.json").write_text(
            json.dumps(
                {
                    "namespace": {
                        "rules": [{"path_glob": "~/.codex/memories/**", "namespace": "codex"}]
                    }
                }
            ),
            encoding="utf-8",
        )
        state = _make_init_state(tmp_path)
        state["provider_rules"] = [
            ("codex", {"path_glob": "~/.codex/memories/**", "namespace": "codex"}),
        ]
        _write_config_and_summary(state, tmp_path)

        out = unstyle(capsys.readouterr().out)
        assert "already managed" in out
        assert "nothing to add" in out

    def test_preset_templates_only_use_allowed_placeholders(self) -> None:
        """Lock the placeholder vocabulary until RFC #304 decides the
        hierarchy format — extending the preset table beyond
        ``{ancestor:1}`` needs an explicit review, not a silent edit."""
        from memtomem.cli.init_cmd import (
            _PROVIDER_RULE_TEMPLATES,
            _VALID_PRESET_PLACEHOLDERS,
        )

        for _category, (_glob, namespace) in _PROVIDER_RULE_TEMPLATES.items():
            if "{" in namespace or "}" in namespace:
                # If placeholders are used, they must be one of the allowed set.
                assert any(p in namespace for p in _VALID_PRESET_PLACEHOLDERS), (
                    f"namespace {namespace!r} uses a placeholder outside "
                    f"_VALID_PRESET_PLACEHOLDERS={_VALID_PRESET_PLACEHOLDERS}"
                )
